insert into questions(id, topic, text) values(1,1,'1. Do you shop for food less frequently than every four days?');
insert into questions(id, topic, text) values(2,1,'2. Do you eat more packaged (frozen or canned) fruits and vegetables than fresh?');
insert into questions(id, topic, text) values(3,1,'3. Do you eat more cooked vegetables than raw?');
insert into questions(id, topic, text) values(4,1,'4. Do you eat vegetables with fewer than two meals daily?');
insert into questions(id, topic, text) values(5,1,'5. Do you buy more non-organic vegetables than organic vegetables?');
insert into questions(id, topic, text) values(6,1,'6. How often do you use a microwave oven?');
insert into questions(id, topic, text) values(7,1,'7. Do you eat white bread more often than whole grain breads?');
insert into questions(id, topic, text) values(8,1,'8. Do you eat quick cook grains such as Rice-A-Roni, Quaker Oats or MINUTE rice more often than slow cooked organic whole grains?');
insert into questions(id, topic, text) values(9,1,'9. How often do you consume pasteurized, homogenized mile or cheeses?');
insert into questions(id, topic, text) values(10,1,'10. How often do you eat non-organic yogurts?');
insert into questions(id, topic, text) values(11,1,'11. Do you eat typical store-bought eggs from cage-raised chickens (as opposed to free-range eggs)?');
insert into questions(id, topic, text) values(12,1,'12. Do you eat non-organic red meat more than once every four days?');
insert into questions(id, topic, text) values(13,1,'13. Do you commonly eat meats (beef, chicken, turkey) from sources other than a free-range and hormone-free source?');
insert into questions(id, topic, text) values(14,1,'14. Do you eat canned fish more frequently than fresh fish?');
insert into questions(id, topic, text) values(15,1,'15. How often do you use commercial salad dressings?');
insert into questions(id, topic, text) values(16,1,'16. How often do you use products containing hydrogenated oils?');
insert into questions(id, topic, text) values(17,1,'17. Do you eat nuts or seeds that are roasted or salted?');
insert into questions(id, topic, text) values(18,1,'18. How often do you use white table sugar as sweetener?');
insert into questions(id, topic, text) values(19,1,'19. How often do you use artificial sweeteners such as Sweet-n-Low, Equal or NutraSweet?');
insert into questions(id, topic, text) values(20,1,'20. Do you use standard white table salt?');
insert into questions(id, topic, text) values(21,1,'21. Do you eat TV dinners or highly processed foods more than three times a week?');
insert into questions(id, topic, text) values(22,1,'22. How often do you eat from fast food restaurants like McDonalds, KFC, Wendys, etc.?');
insert into questions(id, topic, text) values(23,1,'23. How often do you eat snacks form vending machines?');
insert into questions(id, topic, text) values(24,1,'24. Do you drink tap water?');
insert into questions(id, topic, text) values(25,1,'25. How often do you eat some form of store-brought dessert such as ice cream, cookies, donuts, cakes or pies?');
insert into questions(id, topic, text) values(26,2,'1. Do you eat more or less when stressed than when not stressed?');
insert into questions(id, topic, text) values(27,2,'2. Do you worry over job, income or money problems?');
insert into questions(id, topic, text) values(28,2,'3. Are any of your relationships causing you stress?');
insert into questions(id, topic, text) values(29,2,'4. Do you often feel anxious?');
insert into questions(id, topic, text) values(30,2,'5. Do you often get upset when things go wrong?');
insert into questions(id, topic, text) values(31,2,'6. Do you lash out at others?');
insert into questions(id, topic, text) values(32,2,'7. Do you feel your sex drive is lower than normal?');
insert into questions(id, topic, text) values(33,2,'8. Do you feel isolated or lonely?');
insert into questions(id, topic, text) values(34,2,'9. Do you feel stressed due to lack of intimacy in one or more relationships?');
insert into questions(id, topic, text) values(35,2,'10. Have you had reduced contact with friends (feeling antisocial) or an increase in contact because you feel you need to vent your frustrations or stress?');
insert into questions(id, topic, text) values(36,2,'11. Do you take any form of medication prescribed by a physician directly or indirectly related to stress in your life or for psychological disorder?');
insert into questions(id, topic, text) values(37,2,'12. Do you commonly lose more than two days of works a year due to illness?');
insert into questions(id, topic, text) values(38,3,'1. Do you live in the same time zone you were born in?');
insert into questions(id, topic, text) values(39,3,'2. Do you travel across time zones more than once a month?');
insert into questions(id, topic, text) values(40,3,'3. How often do you wake up feeling un-rested and in need of more sleep?');
insert into questions(id, topic, text) values(41,3,'4. Do you commonly go to bed after 10:30pm?');
insert into questions(id, topic, text) values(42,3,'5. Are the times you have bowel movements consistent and predictable on a daily basis?');
insert into questions(id, topic, text) values(43,3,'6. Do you suffer from reduced memory since moving to a new time zone or since traveling across time zones?');
insert into questions(id, topic, text) values(44,3,'7. Has your sense of hunger changed from being hungry at breakfast (upon rising), lunch (midday) and dinner times (sunset) since moving to a new time zones or traveling across time zone frequently (more than once a month)?');
insert into questions(id, topic, text) values(45,3,'8. How often do you wake up at night between 1:00am and 4:00 am and have a hard time falling back to sleep?');
insert into questions(id, topic, text) values(46,3,'9. How often do you tend to have a hard time staying awake in the afternoon after eating lunch?');
insert into questions(id, topic, text) values(47,3,'10. Do you do shift work that requires you to stay up late at night?');
insert into questions(id, topic, text) values(48,4,'1. Do you frequently skip meals?');
insert into questions(id, topic, text) values(49,4,'2. How often do you typically go more than four hours without eating?');
insert into questions(id, topic, text) values(50,4,'3. How often do you skip breakfast?');
insert into questions(id, topic, text) values(51,4,'4. Do you avoid fats when eating?');
insert into questions(id, topic, text) values(52,4,'5. Do you frequently eat carbohydrates (ie. Breads, bagels, cookies, pasta, fruit, cereals, muffins, crackers, chocolate, or candy) by themselves?');
insert into questions(id, topic, text) values(53,4,'6. Do you get hungry or crave sweets within two hours after eating a meal?');
insert into questions(id, topic, text) values(54,4,'7. How often do you consume drinks containing caffeine or sugar (ie: coffee, tea, sodas, fruit juices with sucrose, corn syrup or added sugar)?');
insert into questions(id, topic, text) values(55,4,'8. Have you tried diets to lose weight?');
insert into questions(id, topic, text) values(56,4,'9. Do you have difficulty burning fat around your belly, hips or thighs even with regular exercise?');
insert into questions(id, topic, text) values(57,4,'10. Do you eat your largest meal in the evening?');
insert into questions(id, topic, text) values(58,5,'1. How often do you experience lower abdominal bloating?');
insert into questions(id, topic, text) values(59,5,'2. Do you frequently have loose stools or diarrhea?');
insert into questions(id, topic, text) values(60,5,'3. How often do you experience constipation or stools that are compact or hard to pass?');
insert into questions(id, topic, text) values(61,5,'4. Do you find that you often burp after meals?');
insert into questions(id, topic, text) values(62,5,'5. Do you frequently have gas?');
insert into questions(id, topic, text) values(63,5,'6. Do you crave certain foods such as bread, chocolate, certain fruit, and red meat if you have not eaten them in a day or two ?');
insert into questions(id, topic, text) values(64,5,'7. How often do you have a poor appetite or feel worse after eating? ');
insert into questions(id, topic, text) values(65,5,'8. Do you have an excessive appetite and/ or sweet craving?');
insert into questions(id, topic, text) values(66,5,'9. Do you frequently (more than twice a week) experience abdominal pain, cramps or general abdominal discomfort?');
insert into questions(id, topic, text) values(67,5,'10. How often do you have indigestion, heartburn, or upset stomach?');
insert into questions(id, topic, text) values(68,5,'11. How often do you get a headache after eating?');
insert into questions(id, topic, text) values(69,6,'1. Have you ever been given general anesthesia?');
insert into questions(id, topic, text) values(70,6,'2. Have you ever taken antibiotics?');
insert into questions(id, topic, text) values(71,6,'3. Have you been or are you being treated for any condition requiring that you take medical drugs?');
insert into questions(id, topic, text) values(72,6,'4. In general, are you bowel movements loose, hard or four smelling?');
insert into questions(id, topic, text) values(73,6,'5. Would you consider your life to be:');
insert into questions(id, topic, text) values(74,6,'6. Do you currently suffer from any digestive disorder or frequently have pain in the region above or below the navel:');
insert into questions(id, topic, text) values(75,6,'7. Do you have mercury amalgam fillings in your mouth?');
insert into questions(id, topic, text) values(76,6,'8. Do you have two different kinds of metal in your mouth; ie: gold and silver or mercury amalgam and gold silver?');
insert into questions(id, topic, text) values(77,6,'9. Do you experience itching in the ears, nose or rectum area?');
insert into questions(id, topic, text) values(78,6,'10. Do you have or have you had dandruff in the past year?');
insert into questions(id, topic, text) values(79,6,'11. Do you regularly eat or drink products containing sugar, white flour, processed dairy products?');
insert into questions(id, topic, text) values(80,6,'12. Do you crave sugar, fruit or milk if you than three days?');
insert into questions(id, topic, text) values(81,6,'13. Do you find that regardless of how much you eat you get hungry quickly?');
insert into questions(id, topic, text) values(82,6,'14. In the past year, have you experience soles or heel of the feet), jock itch or a fungal infection under a toenail (thickening of the toenail?');
insert into questions(id, topic, text) values(83,6,'15. Do you ever get a reddening around the mouth or nose area after eating or drinking?');
insert into questions(id, topic, text) values(84,6,'16. Do you experience muscle or joint aches on a regular basis?');
insert into questions(id, topic, text) values(85,6,'17. Do you experience mood swings?');
insert into questions(id, topic, text) values(86,6,'18. Do you snack on sweets or drink coffee, soda pop or sports drinks most days to keep you energy up?');
insert into questions(id, topic, text) values(87,6,'19. Do you suffer from any kind of skin condition?');
insert into questions(id, topic, text) values(88,6,'20. Have you ever had sex or close physical contact with anyone who you know had a fungal infection (including athletes foot, jock itch, dandruff) or parasite infection?');

insert into questions(id, topic, text) values(89,7,'1. I sleep best:');
insert into questions(id, topic, text) values(90,7,'2. I sleep best if:');
insert into questions(id, topic, text) values(91,7,'3. I sleep best and wake up feeling rested:');
insert into questions(id, topic, text) values(92,7,'4. After vigorous exercise, I feel best when i consume:');
insert into questions(id, topic, text) values(93,7,'5. I do best-maintain mental clarity and a sense of well-being for up to 4 hours after a mean-when I eat:');
insert into questions(id, topic, text) values(94,7,'6. If I am tired and consume sugar or sweet foods such as donuts, candy or sweetened drinks without significant amounts of fat or protein:');
insert into questions(id, topic, text) values(95,7,'7. Which statement best describes your disposition toward food in general:');
insert into questions(id, topic, text) values(96,7,'8. I often:');
insert into questions(id, topic, text) values(97,7,'9. Instinctually, I prefer to eat:');
insert into questions(id, topic, text) values(98,7,'10. Which list of fish most appeals to you?');
insert into questions(id, topic, text) values(99,7,'11. When eating dairy products, I feel best after eating:');
insert into questions(id, topic, text) values(100,7,'12. With regard to snacking:');
insert into questions(id, topic, text) values(101,7,'13. Which describes the way you instinctually prefer to start your day in order to feel your best and to have the most energy?');
insert into questions(id, topic, text) values(102,7,'14. Which characteristics best describe you:');
