insert into responses(text, points)values('Yes',1);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',3);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',3);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never or rarely',0);
insert into responses(text, points)values('1 - 2 times per week',2);
insert into responses(text, points)values('3 - 4 times per week',5);
insert into responses(text, points)values('4 + times per week',10);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never or rarely',0);
insert into responses(text, points)values('1 - 2 times per week',1);
insert into responses(text, points)values('3 times per week',3);
insert into responses(text, points)values('3 + times per week',5);
insert into responses(text, points)values('Never or rarely',0);
insert into responses(text, points)values('1 - 2 times per week',1);
insert into responses(text, points)values('3 times per week',3);
insert into responses(text, points)values('3 + times per week',5);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',3);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',3);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',3);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never or rarely',0);
insert into responses(text, points)values('once a week',1);
insert into responses(text, points)values('twice per week',2);
insert into responses(text, points)values('2 + times per week',3);
insert into responses(text, points)values('Never or rarely',0);
insert into responses(text, points)values('once a week',1);
insert into responses(text, points)values('twice per week',2);
insert into responses(text, points)values('2 + times per week',5);
insert into responses(text, points)values('Yes',1);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never or very rarely',0);
insert into responses(text, points)values('once a week',1);
insert into responses(text, points)values('2 - 3 times per week',3);
insert into responses(text, points)values('3 + times per week',5);
insert into responses(text, points)values('Never or rarely',0);
insert into responses(text, points)values('once a week',1);
insert into responses(text, points)values('2 - 3 times per week',5);
insert into responses(text, points)values('3 + times per week',10);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never or rarely',0);
insert into responses(text, points)values('1 - 2 times per week',2);
insert into responses(text, points)values('3 times per week',5);
insert into responses(text, points)values('3 + times per week',10);
insert into responses(text, points)values('Never or rarely',0);
insert into responses(text, points)values('1 - 2 times per week',2);
insert into responses(text, points)values('3 times per week',5);
insert into responses(text, points)values('3 + times per week',10);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never or very rarely',0);
insert into responses(text, points)values('once a week',1);
insert into responses(text, points)values('2 - 3 times per week',3);
insert into responses(text, points)values('3 + times per week',5);
insert into responses(text, points)values('More',10);
insert into responses(text, points)values('Same of less',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',3);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',3);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',15);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never of very rarely',0);
insert into responses(text, points)values('once a week',1);
insert into responses(text, points)values('3 times per week',5);
insert into responses(text, points)values('3 + times per week',10);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',0);
insert into responses(text, points)values('No',5);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never of very rarely',0);
insert into responses(text, points)values('once a week',1);
insert into responses(text, points)values('3 times per week',5);
insert into responses(text, points)values('3 + times per week',10);
insert into responses(text, points)values('Never of very rarely',0);
insert into responses(text, points)values('once a week',1);
insert into responses(text, points)values('3 times per week',5);
insert into responses(text, points)values('3 + times per week',10);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',3);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never of very rarely',0);
insert into responses(text, points)values('1 - 2 times per week',1);
insert into responses(text, points)values('3 times per week',2);
insert into responses(text, points)values('3 + times per week',3);
insert into responses(text, points)values('Never of very rarely',0);
insert into responses(text, points)values('2 times per week',1);
insert into responses(text, points)values('3 times per week ',5);
insert into responses(text, points)values('3 + times per week',10);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never of very rarely',0);
insert into responses(text, points)values('1 cup a day',1);
insert into responses(text, points)values('2 cups per day',3);
insert into responses(text, points)values('More than 2 cups per day',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('once',1);
insert into responses(text, points)values('twice',2);
insert into responses(text, points)values('3 - 5 times',5);
insert into responses(text, points)values('more than five times',10);
insert into responses(text, points)values('Yes',3);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',1);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never of very rarely',0);
insert into responses(text, points)values('1-2 times per week',3);
insert into responses(text, points)values('3 times per week',5);
insert into responses(text, points)values('3 + times per week',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('once a week',1);
insert into responses(text, points)values('3 or more times per week',5);
insert into responses(text, points)values('Never or very rarely',0);
insert into responses(text, points)values('1-2 times per week',3);
insert into responses(text, points)values('3 or more times per week',5);
insert into responses(text, points)values('Yes',3);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',3);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never of very rarely',0);
insert into responses(text, points)values('1-2 times per week',3);
insert into responses(text, points)values('3 times per week',5);
insert into responses(text, points)values('3 + times per week',10);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',20);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Never of very rarely',0);
insert into responses(text, points)values('1-2 times per week',3);
insert into responses(text, points)values('3 times per week',5);
insert into responses(text, points)values('3 + times per week',10);
insert into responses(text, points)values('Never or very rarely',0);
insert into responses(text, points)values('1-2 times per week',3);
insert into responses(text, points)values('3 or more times per week',5);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Stress free ',0);
insert into responses(text, points)values('Mildly stressful',5);
insert into responses(text, points)values('Very stressful',10);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',20);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',5);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',10);
insert into responses(text, points)values('No',0);
insert into responses(text, points)values('Yes',20);
insert into responses(text, points)values('No',0);

insert into responses(text, points)values('when I eat a snack high in protein and fat 1-2 hours before going to sleep',1);
insert into responses(text, points)values('when I eat a snack higher in carbohydrates 3-4 hours before going to sleep',-1);
insert into responses(text, points)values('my dinner is composed mainly of meat with some vegetables or other carbohydrates',1);
insert into responses(text, points)values('my dinner is composed mainly of vegetables or other carbohydrates and comparatively small serving of meat',-1);
insert into responses(text, points)values('if I dont eat sweet deserts like cakes, candy or cookies, If I eat a rich desert that is not overly sweet, such as high-quality full-fat ice cream, I tend to sleep okay.',1);
insert into responses(text, points)values('if I occasionally eat a sweet desert before i go to bed.',-1);
insert into responses(text, points)values('foods or drinks with higher protein and/or fat content, such as a high-protein shake.',1);
insert into responses(text, points)values('foods or drinks higher in carbohydrates(sweeter), such as Gatorade.',-1);
insert into responses(text, points)values('a meat-based meal containing heavier meats such as chiken legs, roast beef and salmon, with a smaller portion of carbohydrate.',1);
insert into responses(text, points)values('a carbohydrate-based meal containing vegetables, bread or rice and a small portion of a lighter meat such as chiken breat or white fish.',-1);
insert into responses(text, points)values('I get a rush of energy, but then I am likely to crash or feel sluggish',1);
insert into responses(text, points)values('I feel better and my energy levels are restored until my next meal',-1);
insert into responses(text, points)values('I love food and live to eat!',1);
insert into responses(text, points)values('I do not fuss over food and I eat to live.',-1);
insert into responses(text, points)values('add salt to my foods.',1);
insert into responses(text, points)values('find that foods are too salty for my liking.',-1);
insert into responses(text, points)values('dark meat, such as the chiken or turkey legs and thighs over the white breat meat.',1);
insert into responses(text, points)values('light meat such as the chiken or turkey breast over the dark leg and thigh meat.',-1);
insert into responses(text, points)values('Anchovy, caviar, herring, mussels, sardines, abalone, clams, crab, caryfish, lobster, mackerel, octopus, oyster, salmon, scallops, shrimp, snail, squid, tuna(dark meat)',1);
insert into responses(text, points)values('White fish, catfish, cod, flounder, haddock, perch, scrod, sole, trout, tuna(white), turbot',-1);
insert into responses(text, points)values('Richer, full fat yogurts and cheeses or desserts.',1);
insert into responses(text, points)values('Lighter, low fat yogurts and cheeses or desserts.',-1);
insert into responses(text, points)values('I tend to do better when I snack between meals or eat more smaller meals throughout the day',1);
insert into responses(text, points)values('I tend to last betweeen meals without snakcing',-1);
insert into responses(text, points)values('A large breakfast that includes protein and fat, such as eggs with sausage or bacon.',1);
insert into responses(text, points)values('A light breakfast such as cereal, fruit, yogurt, breads and possibly some eggs.',-1);
insert into responses(text, points)values('In general, I digest food well, have an appetite for proteins, feel good when eating fats or fatty foods, am more muscular or incluned to gain muscle or strength easily.',1);
insert into responses(text, points)values('I am more lithe of build, prefer light meats and lower fat foods, am more incluned toward endurance athletics.',-1);

